ProcAccessar/Models/Categoria.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProcAccessar.Models;

[Table("tbCategoria")]
public class Categoria
{
    public int CategoriaId { get; set; }

    [Display(Name = "Categoria")]
    public string Descricao { get; set; }
}

ProcAccessar/Models/Processo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProcAccessar.Models;

[Table("tbProcesso")]
public class Processo
{
    public int ProcessoId { get; set; }
    [Display(Name = "Cód.")]
    public int Codigo { get; set; }

    [Display(Name = "Título")]
    [StringLength(100, MinimumLength = 10, ErrorMessage = "O {0} deve ter no mínimo {2} e no máximo {1} caracteres.")]
    public string Titulo { get; set; }

    [Display(Name = "Descrição")]
    [StringLength(200, MinimumLength = 10, ErrorMessage = "O {0} deve ter no mínimo {2} e no máximo {1} caracteres.")]
    public string Descricao { get; set; }

    [Display(Name = "Data")]
    [DataType(DataType.Date, ErrorMessage = "A data foi prenchida!")]
    public DateTime? DataCriacao { get; set; }
    public int CategoriaId { get; set; }


    [Display(Name = "Categoria")]
    public virtual IEnumerable<Categoria> Categorias { get; set; }
}

ProcAccessar/ViewModels/ProcessoListViewModel.cs
using ProcAccessar.Models;
using System.ComponentModel.DataAnnotations;

namespace ProcAccessar.ViewModels;

public class ProcessoListViewModel
{
    [Required(ErrorMessage = "O código do processo é obrigatório!")]
    [Display(Name = "Cod. Processo")]
    public int Codigo { get; set; }

    [Required(ErrorMessage = "Título requerido!")]
    [Display(Name = "Título")]
    public string Titulo { get; set; }

    [Required(ErrorMessage = "Faça uma breve descrição")]
    [Display(Name = "Descrição")]
    [StringLength(100, MinimumLength = 10, ErrorMessage = "O {0} deve ter no mínimo {2} e no máximo {1} caracteres.")]
    public string Descricao { get; set; }

    [Required(ErrorMessage = "Escolha uma data!")]
    [Display(Name = "Data do Processo")]
    [DataType(DataType.Date, ErrorMessage = "Data em formato inválido!")]
    public DateTime? DataCriacao { get; set; }

    public virtual Categoria Categorias { get; set; }
    public virtual IEnumerable<Categoria> Categoria { get; set; }
}

ProcAccessar/ViewModels/ProcessoPesquisaViewModel.cs
using Microsoft.EntityFrameworkCore;
using ProcAccessar.Models;

namespace ProcAccessar.ViewModels;

[Keyless]
public class ProcessoPesquisaViewModel
{
    public List<Processo>? Processos { get; set; }
    public string? PalavraBusca { get; set; }
}

ProcAccessar/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProcAccessar.Models;
using System.Diagnostics;


namespace ProcAccessar.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

ProcAccessar/Controllers/ProcessosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProcAccessar.Context;
using ProcAccessar.Models;
using ProcAccessar.ViewModels;
using ReflectionIT.Mvc.Paging;
using System.Linq;

namespace ProcAccessar.Controllers
{
    public class ProcessosController : Controller
    {
        private readonly AppDbContext _context;

        public ProcessosController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Processos
        //public async Task<IActionResult> Index(string PalavraBusca = "")
        //{
        //    var processos = from p in _context.Processos
        //                    select p;

        //    if (!string.IsNullOrEmpty(PalavraBusca))
        //    {
        //        processos = processos.Where(s => s.Titulo.Contains(PalavraBusca));
        //    }
        //    processos = processos.OrderBy(s => s.Codigo);
        //    return View(await processos.ToListAsync());
        //}

        public async Task<IActionResult> Index(string filter, int pageindex, string sort= "Titulo")
        {
            var resultado = _context.Processos.AsNoTracking().AsQueryable();
            if (!string.IsNullOrEmpty(filter))
            {
                resultado = resultado.Where(s => s.Titulo.Contains(filter));
            }

            var model = await PagingList.CreateAsync(resultado, 5, pageindex, sort, "Titulo");

            model.RouteValue = new RouteValueDictionary { { "filter", filter } };

            return View(model);
        }
       
            public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var processo = await _context.Processos
                .FirstOrDefaultAsync(m => m.ProcessoId == id);
            if (processo == null)
            {
                return NotFound();
            }

            return View(processo);
        }

        // GET: Processos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Processos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProcessoId,Codigo,Titulo,Descricao,DataCriacao,CategoriaId")] Processo processo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(processo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(processo);
        }

        // GET: Processos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var processo = await _context.Processos.FindAsync(id);
            if (processo == null)
            {
                return NotFound();
            }
            return View(processo);
        }

        // POST: Processos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProcessoId,Codigo,Titulo,Descricao,DataCriacao,CategoriaId")] Processo processo)
        {
            if (id != processo.ProcessoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(processo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProcessoExists(processo.ProcessoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(processo);
        }

        // GET: Processos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var processo = await _context.Processos
                .FirstOrDefaultAsync(m => m.ProcessoId == id);
            if (processo == null)
            {
                return NotFound();
            }

            return View(processo);
        }

        // POST: Processos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var processo = await _context.Processos.FindAsync(id);
            _context.Processos.Remove(processo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: ProcessoPesquisaViewModel
        public async Task<IActionResult> Search()
        {
            return View();
        }

        [HttpPost, ActionName("Search")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Search(string palavraBusca)
        {
            return View(_context.Processos.Where(p => p.Titulo.Contains(palavraBusca)).OrderBy(p => p.Titulo));
        }
        private bool ProcessoExists(int id)
        {
            return _context.Processos.Any(e => e.ProcessoId == id);
        }
    }
}

ProcAccessar/Views/Home/Index.cshtml
@model ProcAccessar.Models.Processo
@{
    ViewData["Title"] = "Index";
}

<div class="jumbotron">
    <h1 class="display-4">MP-CE</h1>
    <p class="lead">Processos</p>
    <hr class="my-4">
    <p>Consultas, exclusões e atualizações de processos</p>
</div>

@*
    <div class="row">
    <div class="col-md-4">
    <form asp-action="Index"  asp-controller="Processos">
    <div class="form-group">
    <label asp-for="Codigo" class="control-label"></label>
    <input asp-for="Codigo" class="form-control" placeholder="Código" />
    <span asp-validation-for="Codigo" class="text-danger"></span>
    </div>
    <div class="form-group">
    <input type="submit" value="Search" class="btn btn-primary" />
    </div>
    </form>
    </div>
    </div>*@

ProcAccessar/Views/Processos/Create.cshtml
@model ProcAccessar.Models.Processo

@{
    ViewData["Title"] = "Create";
}

<h1>Criar Processo</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="criarProcesso">
                <hr />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                <div class="codigo">
                    <label asp-for="Codigo" class="control-label"></label>
                    <input asp-for="Codigo" class="form-control" />
                    <span asp-validation-for="Codigo" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="titulo">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" />
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="descricao">
                    <div class="descricao">
                        <label asp-for="Descricao" class="control-label"></label>
                        <input asp-for="Descricao" class="form-control" />
                        <span asp-validation-for="Descricao" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="data">
                    <label asp-for="DataCriacao" class="control-label"></label>
                    <input asp-for="DataCriacao" class="form-control" />
                    <span asp-validation-for="DataCriacao" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="categoriaId">
                    <label asp-for="CategoriaId" class="control-label"></label>
                    <input asp-for="CategoriaId" class="form-control" />
                    <span asp-validation-for="CategoriaId" class="text-danger"></span>
                </div>
            </div>
            <hr />
                <div class="form-group">
                    <input type="submit" value="Salvar Processo" class="btn btn-primary" />
                </div>
            </div>

        </form>
    </div>
</div>

<div class="voltar">
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

ProcAccessar/Views/Processos/Delete.cshtml
@model ProcAccessar.Models.Processo

@{
    ViewData["Title"] = "Delete";
}

<h1>Excluindo Processo</h1>

<h3>Você tem certeza que quer excluir este processo?</h3>
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataCriacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCriacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoriaId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoriaId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProcessoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

ProcAccessar/Views/Processos/Details.cshtml
@model ProcAccessar.Models.Processo

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes do Processo</h1>

<div>
    <h4>Processo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataCriacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCriacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoriaId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoriaId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProcessoId">Edit</a> |
    <a asp-action="Search">Voltar a página de Pesquisa</a>
</div>

ProcAccessar/Views/Processos/Edit.cshtml
@model ProcAccessar.Models.Processo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Processo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProcessoId" />
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataCriacao" class="control-label"></label>
                <input asp-for="DataCriacao" class="form-control" />
                <span asp-validation-for="DataCriacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoriaId" class="control-label"></label>
                <input asp-for="CategoriaId" class="form-control" />
                <span asp-validation-for="CategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProcAccessar/Views/Processos/Index.cshtml
@model IEnumerable<ProcAccessar.Models.Processo>

@{
    ViewData["Title"] = "Index";
}

<h1>Pesquisar Processo</h1>

<p>
    <a asp-action="Create">Novo Processo</a>
</p>

<hr />

<form asp-controller="Processos" asp-action="Index" method="get">
    <p>
        <input class="form-control" type="text" />
        <input type="submit" value="Pesquisar" class="btn btn-primary" />
    </p>
</form>

<hr />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCriacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoriaId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataCriacao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoriaId)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ProcessoId">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.ProcessoId">Detalhar</a> |
                    <a asp-action="Delete" asp-route-id="@item.ProcessoId">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ProcAccessar/Views/Processos/Search.cshtml
@model ProcAccessar.Models.Processo
@{
    ViewData["Title"] = "Pesquisa";
}
<h1>Pesquisa</h1>
<hr />
<div>
    @using (Html.BeginForm())
    {
        @*<p>Digite o nome</p>*@
        <input type="text" name="texto" id="texto" placeholder="Digite a pesquisa" />
        <div><input type="submit" value="Pesquisar" class="btn btn-primary" onclick="pesquisa()"/></div>
    }
</div>

ProcAccessar/Views/Processos/SearchExecuted.cshtml
@model IEnumerable<ProcAccessar.Models.Processo>
@{
    ViewData["Title"] = "SearchExecuted";
 }

<h1>Resultados Obtidos</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCriacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoriaId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataCriacao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoriaId)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ProcessoId">Editar</a> |
                    <a asp-action="Delete" asp-route-id="@item.ProcessoId">Deletar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ProcAccessar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProcAccessar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" src="~/css/create_estilo.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProcAccessar.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProcAccessar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Processos" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Processos" asp-action="Create">Novo Processo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Processos" asp-action="Search">Pesquisa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Footer -->
    <footer class="text-center text-lg-start bg-light text-muted">

        <!-- Section: Links  -->
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <!-- Grid row -->
                <div class="row">
                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-4 col-xl-4">
                        <!-- Content -->
                        <img src="~/images/logo_mp_png_footer.png" />
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-4 col-xl-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Endereço
                        </h6>
                        <p>
                            Ministério Público do Estado do Ceará<br/>
                        Procuradoria Geral de Justiça<br/>
                        Sede Cambeba (Gabinete PGJ, Procuradorias de Justiça)<br/>
                        Av. Gen. Afonso Albuquerque Lima, 130 - Cambeba<br/>
                        CEP: 60.822-325 - Fortaleza, Ceará. Brasil<br/>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-4 col-xl-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Endereço
                        </h6>
                        <p>
                            Ministério Público do Estado do Ceará<br />
                            Procuradoria Geral de Justiça<br />
                            Setores Administrativos<br />
                            Rua Assunção, 1100 - José Bonifácio<br />
                            CEP: 60050-011 - Fortaleza, Ceará. Brasil<br />
                        </p>
                    </div>

                </div>
                <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2021 Copyright:
            <a class="text-reset fw-bold" href="http://www.mpce.mp.br">MP-CE</a> - 
            <a asp-area="" asp-controller="Processos" asp-action="Index">Home</a>
        </div>
        <!-- Copyright -->
    </footer>
  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>